apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

images:
- name: registry.cn-shanghai.aliyuncs.com/invs/choice-editor
  newTag: latest

labels:
- includeSelectors: true
  pairs:
    app: choice-editor
    managed-by: kustomize
